<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXwFpapQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXwFpapQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXwFpapQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXwFpapQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXwFpapQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XwFpapQ',
    'container.build_id' => 'd0a98340',
    'container.build_time' => 1748135344,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXwFpapQ');
